### ISSUE TITLE
cssnano and webpack, make the plugin official

### ISSUE THREAD

**Issue by evilebottnawi** [webpack-contrib/cssnano-webpack-plugin#3]
Hello, I am developer of cssnano and webpack, we want to do `cssnano-webpack-plugin` official and move it in `webpack-contrib` org - https://github.com/webpack-contrib. What do you think about this?

**Comment by lneveu** [comment]
Hello @evilebottnawi,
Sure, I'll be glad to do it! How do you want to proceed?

And what does it mean for the plugin? Will it be maintained by "core" Webpack contributors?

**Comment by evilebottnawi** [comment]
> Sure, I'll be glad to do it! How do you want to proceed?

1. Need send a PR (from you) with new license - example of license https://github.com/webpack-contrib/css-loader/blob/master/LICENSE
2. Add me to admin for project here
3. Add access to publish for me (npm)
4. Migrate repo from here to `webpack-contrib` org (I will do it)

> And what does it mean for the plugin?

Official supporting + compatibility with webpack@5 + multi threading + cachehing + a lot of other features

> Will it be maintained by "core" Webpack contributors?

Yes, but you can continue helping us and you will have access to this repo

**Comment by lneveu** [comment]
Done! Tell me if its ok for you

**Comment by evilebottnawi** [comment]
@lneveu Done, need npm access to publish too

**Comment by lneveu** [comment]
I added you as a maintainer. Should be ok

**Comment by evilebottnawi** [comment]
@lneveu Please enable 2FA for Auth/Writes, safe is important

**Comment by lneveu** [comment]
@evilebottnawi done

**Comment by evilebottnawi** [comment]
@lneveu Because it is not org account (it your account :smile: ), we need to transfer repo for me and I will retransfer it to org

**Comment by evilebottnawi** [comment]
Done, big thanks! In near future we will update code, implement cache and multithreading + many tests and docs

**Comment by lneveu** [comment]
Great! Happy to contribute to Webpack ecosystem :)
